/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:Parameters_Window:437002:
  appc.background(230);
} //_CODE_:Parameters_Window:437002:

public void EpochFieldChagned(GTextField source, GEvent event) { //_CODE_:EpochField:826180:
  epochs = int(EpochField.getText());
} //_CODE_:EpochField:826180:

public void ActivationListChanged(GDropList source, GEvent event) { //_CODE_:ActivationList:754752:
  activation = ActivationList.getSelectedText();
} //_CODE_:ActivationList:754752:

public void LostFunctionListChanged(GDropList source, GEvent event) { //_CODE_:LossFunctionList:713425:
  println("LossFunctionList - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:LossFunctionList:713425:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  Parameters_Window = GWindow.getWindow(this, "Parameters", 0, 0, 240, 250, JAVA2D);
  Parameters_Window.noLoop();
  Parameters_Window.setActionOnClose(G4P.KEEP_OPEN);
  Parameters_Window.addDrawHandler(this, "win_draw1");
  Hyper_Paramters_Label = new GLabel(Parameters_Window, 8, 4, 101, 20);
  Hyper_Paramters_Label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Hyper_Paramters_Label.setText("Hyper Paramters");
  Hyper_Paramters_Label.setLocalColorScheme(GCScheme.RED_SCHEME);
  Hyper_Paramters_Label.setOpaque(false);
  Epoch_Label = new GLabel(Parameters_Window, 7, 35, 58, 20);
  Epoch_Label.setText("Epochs");
  Epoch_Label.setOpaque(false);
  EpochField = new GTextField(Parameters_Window, 69, 36, 68, 19, G4P.SCROLLBARS_NONE);
  EpochField.setText("0");
  EpochField.setPromptText("(Numbers Only)");
  EpochField.setOpaque(true);
  EpochField.addEventHandler(this, "EpochFieldChagned");
  Activation_label = new GLabel(Parameters_Window, 7, 60, 57, 20);
  Activation_label.setText("Activation");
  Activation_label.setOpaque(false);
  ActivationList = new GDropList(Parameters_Window, 68, 60, 149, 80, 3, 10);
  ActivationList.setItems(loadStrings("list_754752"), 0);
  ActivationList.addEventHandler(this, "ActivationListChanged");
  CostLabel = new GLabel(Parameters_Window, 7, 84, 60, 20);
  CostLabel.setText("Loss");
  CostLabel.setOpaque(false);
  LossFunctionList = new GDropList(Parameters_Window, 70, 85, 146, 60, 2, 10);
  LossFunctionList.setItems(loadStrings("list_713425"), 0);
  LossFunctionList.addEventHandler(this, "LostFunctionListChanged");
  Parameters_Window.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow Parameters_Window;
GLabel Hyper_Paramters_Label; 
GLabel Epoch_Label; 
GTextField EpochField; 
GLabel Activation_label; 
GDropList ActivationList; 
GLabel CostLabel; 
GDropList LossFunctionList; 
